"""Generated SSH defaults plus durable user overrides.

The old blueprint was one mutable raw file, so changing the seed in code could
not safely update an existing installation. The split model keeps only custom
content as authoritative data and materializes the effective legacy file for
older service versions and operational inspection.

Managed defaults are generated on every read. Deploying a newer managed version
therefore self-heals every client without rewriting user-owned directives.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

BLUEPRINT_SCHEMA_VERSION = 1
MANAGED_VERSION = 2

MANAGED_BEGIN_PREFIX = "# BEGIN DVW MANAGED DEFAULTS"
MANAGED_BEGIN = f"# BEGIN DVW MANAGED DEFAULTS version={MANAGED_VERSION}"
MANAGED_END = "# END DVW MANAGED DEFAULTS"

_MANAGED_BLOCK_V2 = f"""\
{MANAGED_BEGIN_PREFIX} version=2
# Generated by dvw-catalog. Put shared overrides above this block.
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
  ServerAliveInterval 5
  ServerAliveCountMax 3
{MANAGED_END}
"""

# Keep old entries byte-for-byte when adding a managed version. They let a
# newer service recover custom content from an older materialized file if the
# authoritative custom file is lost.
_MANAGED_BLOCKS = {
    2: _MANAGED_BLOCK_V2,
}
MANAGED_BLOCK = _MANAGED_BLOCKS[MANAGED_VERSION]

_LEGACY_PREAMBLE = """\
# dvw blueprint — served by dvw-catalog (GET /v1/blueprint).
# Edit via `dvw -l`/the service; all machines pick it up on the next dvw call.
# Personal/host-specific config stays in ~/.ssh/config; only put shared
# config here.

"""

_LEGACY_BLOCK_V1 = """\
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
"""

_LEGACY_BLOCK_V2 = """\
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
  ServerAliveInterval 5
  ServerAliveCountMax 3
"""

_KNOWN_LEGACY_DOCUMENTS = {
    _LEGACY_PREAMBLE + _LEGACY_BLOCK_V1,
    _LEGACY_PREAMBLE + _LEGACY_BLOCK_V2,
}


class BlueprintConflictError(ValueError):
    """The submitted revision or managed section is not writable."""


class FutureBlueprintVersionError(RuntimeError):
    """On-disk state was written by a newer managed-blueprint implementation."""


@dataclass(frozen=True)
class BlueprintSnapshot:
    content: str
    custom_content: str
    version: int
    managed_version: int
    revision: str
    migration_status: str


class BlueprintStore:
    def __init__(
        self,
        effective_path: Path,
        custom_path: Path,
        meta_path: Path,
        legacy_backup_path: Path,
    ):
        self.effective_path = effective_path
        self.custom_path = custom_path
        self.meta_path = meta_path
        self.legacy_backup_path = legacy_backup_path

    def read(self) -> BlueprintSnapshot:
        status = self._ensure_state()
        custom = self.custom_path.read_text()
        _reject_managed_markers(custom)
        effective = render_effective(custom)
        self._materialize(effective)
        return self._snapshot(custom, effective, status)

    def write_custom(
        self, content: str, expected_revision: str | None = None
    ) -> BlueprintSnapshot:
        current = self.read()
        self._check_revision(current.revision, expected_revision)
        _reject_managed_markers(content)
        _atomic_write(self.custom_path, content)
        effective = render_effective(content)
        self._materialize(effective)
        return self._snapshot(content, effective, "custom_updated")

    def write_effective_compat(
        self, content: str, expected_revision: str | None = None
    ) -> BlueprintSnapshot:
        """Compatibility PUT for clients that still submit the whole blueprint."""
        custom = extract_custom_content(content)
        return self.write_custom(custom, expected_revision)

    def _snapshot(
        self, custom: str, effective: str, migration_status: str
    ) -> BlueprintSnapshot:
        digest = hashlib.sha256(effective.encode()).hexdigest()
        return BlueprintSnapshot(
            content=effective,
            custom_content=custom,
            version=int(self.effective_path.stat().st_mtime),
            managed_version=MANAGED_VERSION,
            revision=f"sha256:{digest}",
            migration_status=migration_status,
        )

    def _ensure_state(self) -> str:
        self.effective_path.parent.mkdir(parents=True, exist_ok=True)
        meta = self._read_meta()
        if meta is not None:
            schema = meta.get("schema_version")
            managed = meta.get("managed_version")
            if not isinstance(schema, int) or not isinstance(managed, int):
                raise FutureBlueprintVersionError("invalid SSH blueprint metadata")
            if schema > BLUEPRINT_SCHEMA_VERSION:
                raise FutureBlueprintVersionError(
                    f"SSH blueprint schema {schema} is newer than this service "
                    f"supports ({BLUEPRINT_SCHEMA_VERSION})"
                )
            if managed > MANAGED_VERSION:
                raise FutureBlueprintVersionError(
                    f"SSH managed defaults v{managed} are newer than this "
                    f"service supports (v{MANAGED_VERSION})"
                )

        status = "current"
        if not self.custom_path.exists():
            if self.effective_path.exists():
                legacy = self.effective_path.read_text()
                if not self.legacy_backup_path.exists():
                    _atomic_write(self.legacy_backup_path, legacy)
                custom, status = _migrate_legacy_content(legacy)
            else:
                custom = ""
                status = "fresh_initialized"
            _atomic_write(self.custom_path, custom)
        elif meta is None:
            # Recovery after a crash between the custom and metadata writes.
            # Preserve any pre-split effective file before rematerializing it.
            if self.effective_path.exists() and not self.legacy_backup_path.exists():
                _atomic_write(self.legacy_backup_path, self.effective_path.read_text())
            status = "state_recovered"

        if (
            meta is None
            or meta["schema_version"] < BLUEPRINT_SCHEMA_VERSION
            or meta["managed_version"] < MANAGED_VERSION
        ):
            if meta is not None:
                status = (
                    "schema_upgraded"
                    if meta["schema_version"] < BLUEPRINT_SCHEMA_VERSION
                    else "managed_upgraded"
                )
            # Write the forward-version guard before the generated effective
            # file. A rollback then refuses to downgrade instead of replacing a
            # newer materialization with older defaults.
            _atomic_write(
                self.meta_path,
                json.dumps(
                    {
                        "schema_version": BLUEPRINT_SCHEMA_VERSION,
                        "managed_version": MANAGED_VERSION,
                    },
                    indent=2,
                )
                + "\n",
            )
        return status

    def _read_meta(self) -> dict | None:
        if not self.meta_path.exists():
            return None
        try:
            raw = json.loads(self.meta_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            raise FutureBlueprintVersionError(
                f"cannot read SSH blueprint metadata: {exc}"
            ) from exc
        if not isinstance(raw, dict):
            raise FutureBlueprintVersionError("invalid SSH blueprint metadata")
        return raw

    def _materialize(self, effective: str) -> None:
        if (
            self.effective_path.exists()
            and self.effective_path.read_text() == effective
        ):
            return
        _atomic_write(self.effective_path, effective)

    @staticmethod
    def _check_revision(current: str, expected: str | None) -> None:
        if expected is None or expected == "*":
            return
        normalized = expected.strip().strip('"')
        if normalized != current:
            raise BlueprintConflictError(
                "SSH blueprint revision changed; fetch it again before updating"
            )


def render_effective(custom: str) -> str:
    if not custom:
        return MANAGED_BLOCK
    return custom.rstrip("\n") + "\n\n" + MANAGED_BLOCK


def extract_custom_content(content: str) -> str:
    """Remove one exact generated suffix; reject edited or ambiguous markers."""
    has_marker = MANAGED_BEGIN_PREFIX in content or MANAGED_END in content
    if not has_marker:
        return content
    if (
        content.count(MANAGED_BEGIN) != 1
        or content.count(MANAGED_END) != 1
        or not content.endswith(MANAGED_BLOCK)
    ):
        raise BlueprintConflictError(
            "the DVW managed SSH section cannot be edited; put overrides above it"
        )
    prefix = content[: -len(MANAGED_BLOCK)]
    if not prefix:
        return ""
    return prefix.rstrip("\n") + "\n"


def _reject_managed_markers(content: str) -> None:
    if MANAGED_BEGIN_PREFIX in content or MANAGED_END in content:
        raise BlueprintConflictError(
            "custom SSH content cannot contain DVW managed-section markers"
        )


def _migrate_legacy_content(content: str) -> tuple[str, str]:
    for version in sorted(_MANAGED_BLOCKS, reverse=True):
        block = _MANAGED_BLOCKS[version]
        if content.endswith(block):
            prefix = content[: -len(block)]
            custom = "" if not prefix else prefix.rstrip("\n") + "\n"
            return custom, "managed_materialization_recovered"
    if content in _KNOWN_LEGACY_DOCUMENTS:
        return "", "legacy_defaults_removed"

    # Longer v2 first: its v1 prefix would otherwise leave the keepalive lines
    # behind as invalid top-level options.
    for block in (_LEGACY_BLOCK_V2, _LEGACY_BLOCK_V1):
        if block in content:
            custom = content.replace(block, "", 1)
            custom = custom.removeprefix(_LEGACY_PREAMBLE)
            return custom.lstrip("\n"), "legacy_defaults_removed"

    # Unknown configurations are data, never debris. Keep every byte as custom
    # content and append generated defaults; first-value-wins preserves any
    # intentional overrides already present in the legacy file.
    return content, "legacy_preserved"


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise

    try:
        dfd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(dfd)
        finally:
            os.close(dfd)
    except OSError:
        pass
