"""Generated SSH defaults plus durable user overrides.

The old blueprint was one mutable raw file, so changing the seed in code could
not safely update an existing installation. The split model keeps only custom
content as authoritative data and materializes the effective legacy file for
older service versions and operational inspection.

Managed defaults are generated on every read. Deploying a newer managed version
therefore self-heals every client without rewriting user-owned directives.

Note that `read()` mutates the data dir: it migrates legacy state, sanitizes the
custom file and rematerializes the effective file. A GET is therefore not a
read-only operation on disk, and the data dir must be writable.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import re
import tempfile
import threading
from dataclasses import dataclass
from pathlib import Path

BLUEPRINT_SCHEMA_VERSION = 1
MANAGED_VERSION = 3

MANAGED_BEGIN_PREFIX = "# BEGIN DVW MANAGED DEFAULTS"
MANAGED_END = "# END DVW MANAGED DEFAULTS"

_MANAGED_BLOCK_V2 = f"""\
{MANAGED_BEGIN_PREFIX} version=2
# Generated by dvw-catalog. Put shared overrides above this block.
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
  ServerAliveInterval 5
  ServerAliveCountMax 3
{MANAGED_END}
"""

# v3 adds the clipboard-bridge reverse forward (spec:
# docs/superpowers/specs/2026-08-27-clipboard-bridge-design.md). %d is the
# client user's home. The Match exec guard requests the forward only when a
# clipd socket exists locally: a clipd-less client (jumpi, phones) must not
# bind the container socket, or its attach would steal the bridge from a
# desktop client that can actually serve images (devpod's sshd unlinks the
# previous socket on every new bind — last writer wins).
_MANAGED_BLOCK_V3 = f"""\
{MANAGED_BEGIN_PREFIX} version=3
# Generated by dvw-catalog. Put shared overrides above this block.
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
  ServerAliveInterval 5
  ServerAliveCountMax 3
Match host "*.devpod" exec "test -S %d/.dvw/clip.sock"
  RemoteForward /tmp/dvw-clip.sock %d/.dvw/clip.sock
{MANAGED_END}
"""

# Keep old entries byte-for-byte when adding a managed version, so the
# compatibility PUT still accepts a whole document generated by an older
# service (a client can hold one between its GET and its PUT).
_MANAGED_BLOCKS = {
    2: _MANAGED_BLOCK_V2,
    3: _MANAGED_BLOCK_V3,
}
MANAGED_BLOCK = _MANAGED_BLOCKS[MANAGED_VERSION]

# Matches a whole generated block of any version, wherever it sits and however
# its final line is terminated. Migration and sanitizing use this instead of an
# exact suffix compare: a copy that lost or gained a trailing newline (the
# documented `scp ssh-blueprint.conf` seeding path produces one, because the
# client writes its local copy with `printf '%s'`) must still be recognized as
# generated content rather than preserved as custom data.
_MANAGED_BLOCK_RE = re.compile(
    rf"^{re.escape(MANAGED_BEGIN_PREFIX)}(?P<attrs>[^\n]*)\n"
    rf".*?^{re.escape(MANAGED_END)}[^\n]*\n?",
    re.DOTALL | re.MULTILINE,
)
_MANAGED_VERSION_RE = re.compile(r"version=(\d+)")

_LEGACY_PREAMBLE = """\
# dvw blueprint — served by dvw-catalog (GET /v1/blueprint).
# Edit via `dvw -l`/the service; all machines pick it up on the next dvw call.
# Personal/host-specific config stays in ~/.ssh/config; only put shared
# config here.

"""

# The header dvw wrote before the catalog service existed, when the blueprint
# was synced through Dropbox. Still on deployed installs (confirmed against the
# live vossisrv blueprint). Recognized so migration drops it with the rest of
# the old defaults instead of preserving it as operator content: it would
# otherwise survive as "custom config" telling every reader to edit a path that
# is no longer the source of truth. The original file is kept in
# ssh-blueprint.legacy.bak either way.
_LEGACY_PREAMBLE_DROPBOX = """\
# dvw blueprint — synced from ~/Dropbox-remote/dvw/ssh-blueprint.conf.
# Edit there; all machines pick it up on the next `dvw` invocation.
# Personal/host-specific config stays in ~/.ssh/config; only put shared
# config here.

"""

_LEGACY_PREAMBLES = (_LEGACY_PREAMBLE, _LEGACY_PREAMBLE_DROPBOX)

_LEGACY_BLOCK_V1 = """\
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
"""

_LEGACY_BLOCK_V2 = """\
Host *.devpod
  ControlMaster auto
  ControlPath ~/.ssh/cm-%r@%h:%p
  ControlPersist 10m
  ServerAliveInterval 5
  ServerAliveCountMax 3
"""

_KNOWN_LEGACY_DOCUMENTS = {
    preamble + block
    for preamble in _LEGACY_PREAMBLES
    for block in (_LEGACY_BLOCK_V1, _LEGACY_BLOCK_V2)
}


class BlueprintConflictError(ValueError):
    """The submitted revision or managed section is not writable."""


class FutureBlueprintVersionError(RuntimeError):
    """On-disk state was written by a newer managed-blueprint implementation."""


@dataclass(frozen=True)
class BlueprintSnapshot:
    content: str
    custom_content: str
    version: int
    managed_version: int
    revision: str
    migration_status: str


class BlueprintStore:
    def __init__(
        self,
        effective_path: Path,
        custom_path: Path,
        meta_path: Path,
        legacy_backup_path: Path,
    ):
        self.effective_path = effective_path
        self.custom_path = custom_path
        self.meta_path = meta_path
        self.legacy_backup_path = legacy_backup_path
        # A threading lock, not an asyncio one, because the work runs in a
        # worker thread. Cancelling the awaiting coroutine (a disconnected
        # client, which Starlette turns into task cancellation) cannot stop that
        # thread — an asyncio.Lock would be released while its thread was still
        # mid-write, and the next request would interleave with it. Holding the
        # lock inside the thread ties it to the work instead of to the waiter.
        # RLock because write_custom() re-enters through read().
        self._lock = threading.RLock()

    # ---- async service API ------------------------------------------------
    # Blocking file I/O hops to a thread so an fsync can't stall the event loop.

    async def aread(self) -> BlueprintSnapshot:
        return await asyncio.to_thread(self.read)

    async def awrite_custom(
        self, content: str, expected_revision: str | None = None
    ) -> BlueprintSnapshot:
        return await asyncio.to_thread(self.write_custom, content, expected_revision)

    async def awrite_effective_compat(
        self, content: str, expected_revision: str | None = None
    ) -> BlueprintSnapshot:
        return await asyncio.to_thread(
            self.write_effective_compat, content, expected_revision
        )

    # ---- implementation ---------------------------------------------------

    def read(self) -> BlueprintSnapshot:
        with self._lock:
            status = self._ensure_state()
            custom = self.custom_path.read_text()
            sanitized = _strip_managed_blocks(custom)
            if sanitized != custom:
                # Generated content must never be authoritative custom data.
                # Repair it here instead of raising: a rejected read has no
                # recovery path through the API, so it would wedge every future
                # GET on state the operator cannot see or reach.
                _atomic_write(self.custom_path, sanitized)
                custom = sanitized
                status = "custom_sanitized"
            effective = render_effective(custom)
            self._materialize(effective)
            return self._snapshot(custom, effective, status)

    def write_custom(
        self, content: str, expected_revision: str | None = None
    ) -> BlueprintSnapshot:
        with self._lock:
            current = self.read()
            self._check_revision(current.revision, expected_revision)
            _reject_managed_markers(content)
            _atomic_write(self.custom_path, content)
            effective = render_effective(content)
            self._materialize(effective)
            return self._snapshot(content, effective, "custom_updated")

    def write_effective_compat(
        self, content: str, expected_revision: str | None = None
    ) -> BlueprintSnapshot:
        """Compatibility PUT for clients that still submit the whole blueprint."""
        with self._lock:
            custom = extract_custom_content(content)
            return self.write_custom(custom, expected_revision)

    def _snapshot(
        self, custom: str, effective: str, migration_status: str
    ) -> BlueprintSnapshot:
        digest = hashlib.sha256(effective.encode()).hexdigest()
        return BlueprintSnapshot(
            content=effective,
            custom_content=custom,
            version=int(self.effective_path.stat().st_mtime),
            managed_version=MANAGED_VERSION,
            revision=f"sha256:{digest}",
            migration_status=migration_status,
        )

    def _ensure_state(self) -> str:
        self.effective_path.parent.mkdir(parents=True, exist_ok=True)
        meta = self._read_meta()
        if meta is not None:
            schema = meta.get("schema_version")
            managed = meta.get("managed_version")
            if not isinstance(schema, int) or not isinstance(managed, int):
                raise FutureBlueprintVersionError("invalid SSH blueprint metadata")
            if schema > BLUEPRINT_SCHEMA_VERSION:
                raise FutureBlueprintVersionError(
                    f"SSH blueprint schema {schema} is newer than this service "
                    f"supports ({BLUEPRINT_SCHEMA_VERSION})"
                )
            if managed > MANAGED_VERSION:
                raise FutureBlueprintVersionError(
                    f"SSH managed defaults v{managed} are newer than this "
                    f"service supports (v{MANAGED_VERSION})"
                )

        status = "current"
        if not self.custom_path.exists():
            if self.effective_path.exists():
                legacy = self.effective_path.read_text()
                if not self.legacy_backup_path.exists():
                    _atomic_write(self.legacy_backup_path, legacy)
                custom, status = _migrate_legacy_content(legacy)
            else:
                custom = ""
                status = "fresh_initialized"
            _atomic_write(self.custom_path, custom)
        elif meta is None:
            # Recovery after a crash between the custom and metadata writes.
            # Preserve any pre-split effective file before rematerializing it.
            if self.effective_path.exists() and not self.legacy_backup_path.exists():
                _atomic_write(self.legacy_backup_path, self.effective_path.read_text())
            status = "state_recovered"

        if (
            meta is None
            or meta["schema_version"] < BLUEPRINT_SCHEMA_VERSION
            or meta["managed_version"] < MANAGED_VERSION
        ):
            if meta is not None:
                status = (
                    "schema_upgraded"
                    if meta["schema_version"] < BLUEPRINT_SCHEMA_VERSION
                    else "managed_upgraded"
                )
            # Write the forward-version guard before the generated effective
            # file. A rollback then refuses to downgrade instead of replacing a
            # newer materialization with older defaults.
            _atomic_write(
                self.meta_path,
                json.dumps(
                    {
                        "schema_version": BLUEPRINT_SCHEMA_VERSION,
                        "managed_version": MANAGED_VERSION,
                    },
                    indent=2,
                )
                + "\n",
            )
        return status

    def _read_meta(self) -> dict | None:
        if not self.meta_path.exists():
            return None
        try:
            raw = json.loads(self.meta_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            raise FutureBlueprintVersionError(
                f"cannot read SSH blueprint metadata: {exc}"
            ) from exc
        if not isinstance(raw, dict):
            raise FutureBlueprintVersionError("invalid SSH blueprint metadata")
        return raw

    def _materialize(self, effective: str) -> None:
        if (
            self.effective_path.exists()
            and self.effective_path.read_text() == effective
        ):
            return
        _atomic_write(self.effective_path, effective)

    @staticmethod
    def _check_revision(current: str, expected: str | None) -> None:
        if expected is None or expected == "*":
            return
        normalized = expected.strip().strip('"')
        if normalized != current:
            raise BlueprintConflictError(
                "SSH blueprint revision changed; fetch it again before updating"
            )


def render_effective(custom: str) -> str:
    if not custom:
        return MANAGED_BLOCK
    return custom.rstrip("\n") + "\n\n" + MANAGED_BLOCK


def extract_custom_content(content: str) -> str:
    """Strip one verbatim generated suffix; reject an edited managed section.

    Trailing newlines are normalized before the compare. A round trip through a
    shell (`$(curl ...)`) or an editor changes them without touching a single
    directive, and answering that with "the managed section cannot be edited"
    would be both a false alarm and a misleading one. Any known managed version
    is accepted so a client holding an older materialization can still PUT.
    """
    if MANAGED_BEGIN_PREFIX not in content and MANAGED_END not in content:
        return content
    _guard_future_managed_version(content)
    normalized = content.rstrip("\n") + "\n"
    if (
        normalized.count(MANAGED_BEGIN_PREFIX) == 1
        and normalized.count(MANAGED_END) == 1
    ):
        for version in sorted(_MANAGED_BLOCKS, reverse=True):
            block = _MANAGED_BLOCKS[version]
            if normalized.endswith(block):
                prefix = normalized[: -len(block)]
                return "" if not prefix.strip() else prefix.rstrip("\n") + "\n"
    raise BlueprintConflictError(
        "the DVW managed SSH section cannot be edited; put overrides above it"
    )


def _reject_managed_markers(content: str) -> None:
    if MANAGED_BEGIN_PREFIX in content or MANAGED_END in content:
        raise BlueprintConflictError(
            "custom SSH content cannot contain DVW managed-section markers"
        )


def _guard_future_managed_version(content: str) -> None:
    """Refuse to strip a block generated by a newer service.

    Recognizing every version is what stops a stray newline from wedging a
    read, but it must not become a downgrade path: stripping a v3 block and
    re-emitting v2 defaults would silently roll back the SSH config of every
    client that syncs afterwards. Read the version out of the marker and stop.
    """
    for match in _MANAGED_BLOCK_RE.finditer(content):
        found = _MANAGED_VERSION_RE.search(match.group("attrs"))
        if found and int(found.group(1)) > MANAGED_VERSION:
            raise FutureBlueprintVersionError(
                f"SSH managed defaults v{found.group(1)} are newer than this "
                f"service supports (v{MANAGED_VERSION})"
            )


def _strip_managed_blocks(content: str) -> str:
    """Drop every generated block, leaving only operator-authored content."""
    _guard_future_managed_version(content)
    stripped = _MANAGED_BLOCK_RE.sub("", content)
    if stripped == content:
        return content
    return "" if not stripped.strip() else stripped.rstrip("\n") + "\n"


def _migrate_legacy_content(content: str) -> tuple[str, str]:
    if MANAGED_BEGIN_PREFIX in content or MANAGED_END in content:
        # A materialized effective file, not a pre-split blueprint: recover the
        # custom part rather than treating generated defaults as user data.
        return _strip_managed_blocks(content), "managed_materialization_recovered"
    if content in _KNOWN_LEGACY_DOCUMENTS:
        return "", "legacy_defaults_removed"

    # Longer v2 first: its v1 prefix would otherwise leave the keepalive lines
    # behind as invalid top-level options.
    for block in (_LEGACY_BLOCK_V2, _LEGACY_BLOCK_V1):
        index = content.find(block)
        if index < 0:
            continue
        # Only strip the stanza when nothing was added inside it. An operator
        # who appended `ForwardAgent yes` to the shared `Host *.devpod` block
        # leaves an indented line directly after the defaults; removing the
        # `Host` header above it would re-file that directive at the top of the
        # document, where OpenSSH applies it to EVERY host rather than to the
        # devpods. Widening the scope of someone's SSH options is worse than
        # keeping a duplicate stanza, so an edited block falls through to
        # `legacy_preserved` below: the operator's whole block is kept verbatim
        # and the generated defaults are appended after it, where
        # first-value-wins leaves their intent authoritative.
        if content[index + len(block) :].startswith((" ", "\t")):
            break
        custom = content[:index] + content[index + len(block) :]
        for preamble in _LEGACY_PREAMBLES:
            if custom.startswith(preamble):
                custom = custom[len(preamble) :]
                break
        return custom.lstrip("\n"), "legacy_defaults_removed"

    # Unknown configurations are data, never debris. Keep every byte as custom
    # content and append generated defaults; first-value-wins preserves any
    # intentional overrides already present in the legacy file.
    return content, "legacy_preserved"


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise

    try:
        dfd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(dfd)
        finally:
            os.close(dfd)
    except OSError:
        pass
